version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - db.env

  site:
    build:
      dockerfile: host_website.dockerfile
      context: .
    env_file:
      - site.env
    ports:
      - 8000:4000

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080