version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  site:
    build:
      dockerfile: host_website.dockerfile
      context: .
    env_file:
      - site.env
    ports:
      - 80:4000
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

volumes: 
  pgdata:

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080